# Limpieza de datos

Importacion de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Carga de ficheros

In [2]:
# carga del dataset1: df_Educ (el de origen). En esta parte, procedo a "limpiar" todo lo que hemos visto en el análisis preliminar.

df_Educ = pd.read_csv('../data/raw/India_Education_Statistics.csv')

In [3]:
# carga del dataset2: df_Rank_final

df_Rank_final = pd.read_csv('../data/raw/df_Rank_final.csv')

# Limpieza de datos

1. df_Rank_final: Eliminación de los registros correspondientes al Año = 2020. Genero el nuevo df_Rank_final2

In [4]:
df_Rank_final

,Institute ID,Institute Name,TLR,RPC,GO,OI,PERCEPTION,City,State,Score,Rank,Año
0,IR-O-U-0456,Indian Institute of Technology Madras,85.61,92.51,86.32,63.57,97.13,Chennai,Tamil Nadu,86.76,1,2020
1,IR-O-U-0220,Indian Institute of Science,79.13,91.48,78.23,58.39,100.00,Bengaluru,Karnataka,82.67,2,2020
2,IR-O-U-0306,Indian Institute of Technology Bombay,83.52,87.81,80.86,57.48,91.96,Mumbai,Maharashtra,82.52,3,2020
3,IR-O-I-1074,Indian Institute of Technology Delhi,84.02,84.46,75.07,67.97,93.89,New Delhi,Delhi,81.75,4,2020
4,IR-O-I-1075,Indian Institute of Technology Kanpur,80.50,75.23,80.74,56.97,79.30,Kanpur,Uttar Pradesh,76.50,5,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
595,IR-O-U-0217,Christ University,56.19,28.34,65.44,74.23,37.84,Bengaluru,Karnataka,49.65,96,2025
596,IR-O-U-0055,National Institute of Technology Silchar,53.21,45.07,70.76,54.17,4.63,Silchar,Assam,49.51,97,2025
597,IR-O-U-0749,Manipal University Jaipur,63.48,33.80,64.04,66.76,7.11,Jaipur,Rajasthan,49.38,98,2025
598,IR-O-U-0739,Madan Mohan Malaviya University of Technology,67.91,18.82,70.37,71.73,18.48,Gorakhpur,Uttar Pradesh,49.11,99,2025
599,IR-O-U-0688,All India Institute of Medical Sciences Bhuban...,69.14,25.45,58.25,69.89,20.28,Khordha,Odisha,49.04,100,2025

In [5]:
# El fichero de 2020 es idéntico al de 2021, se elimina por ser un duplicado. Creo el df_Rank_final2:
df_Rank_final2 = df_Rank_final[df_Rank_final['Año'] != 2020].reset_index(drop=True)

print(df_Rank_final2.shape)        # Debería ser (500, 12)
print(df_Rank_final2['Año'].unique())  # [2021, 2022, 2023, 2024, 2025]

(500, 12)
[2021 2022 2023 2024 2025]

In [6]:
df_Rank_final2.head()

,Institute ID,Institute Name,TLR,RPC,GO,OI,PERCEPTION,City,State,Score,Rank,Año
0,IR-O-U-0456,Indian Institute of Technology Madras,85.61,92.51,86.32,63.57,97.13,Chennai,Tamil Nadu,86.76,1,2021
1,IR-O-U-0220,Indian Institute of Science,79.13,91.48,78.23,58.39,100.00,Bengaluru,Karnataka,82.67,2,2021
2,IR-O-U-0306,Indian Institute of Technology Bombay,83.52,87.81,80.86,57.48,91.96,Mumbai,Maharashtra,82.52,3,2021
3,IR-O-I-1074,Indian Institute of Technology Delhi,84.02,84.46,75.07,67.97,93.89,New Delhi,Delhi,81.75,4,2021
4,IR-O-I-1075,Indian Institute of Technology Kanpur,80.50,75.23,80.74,56.97,79.30,Kanpur,Uttar Pradesh,76.50,5,2021

In [7]:
df_Rank_final2.tail()

,Institute ID,Institute Name,TLR,RPC,GO,OI,PERCEPTION,City,State,Score,Rank,Año
495,IR-O-U-0217,Christ University,56.19,28.34,65.44,74.23,37.84,Bengaluru,Karnataka,49.65,96,2025
496,IR-O-U-0055,National Institute of Technology Silchar,53.21,45.07,70.76,54.17,4.63,Silchar,Assam,49.51,97,2025
497,IR-O-U-0749,Manipal University Jaipur,63.48,33.80,64.04,66.76,7.11,Jaipur,Rajasthan,49.38,98,2025
498,IR-O-U-0739,Madan Mohan Malaviya University of Technology,67.91,18.82,70.37,71.73,18.48,Gorakhpur,Uttar Pradesh,49.11,99,2025
499,IR-O-U-0688,All India Institute of Medical Sciences Bhuban...,69.14,25.45,58.25,69.89,20.28,Khordha,Odisha,49.04,100,2025

2. df_Educ: modificación de algunas variables

In [8]:
df_Educ.head()

,Table Name,State Code,District Code,Tehsil Code,Area Name,Total/ Rural/ Urban,Age-group,Total - Persons,Total - Males,Total - Females,...,Educational level - Non-technical diploma or certificate not equal to degree - Females,Educational level - Technical diploma or certificate not equal to degree - Persons,Educational level - Technical diploma or certificate not equal to degree - Males,Educational level - Technical diploma or certificate not equal to degree - Females,Educational level - Graduate & above - Persons,Educational level - Graduate & above - Males,Educational level - Graduate & above - Females,Educational level - Unclassified - Persons,Educational level - Unclassified - Males,Educational level - Unclassified - Females
0,C2308,0,0,0,INDIA,Total,All ages,1028610328,532156772,496453556,...,127542,3666680,2900839,765841,37670147,25533308,12136839,97756,67969,29787
1,C2308,0,0,0,INDIA,Total,0-6,163819614,84999203,78820411,...,0,0,0,0,0,0,0,0,0,0
2,C2308,0,0,0,INDIA,Total,7,23045028,11910330,11134698,...,0,0,0,0,0,0,0,2743,1513,1230
3,C2308,0,0,0,INDIA,Total,8,31031074,16174274,14856800,...,0,0,0,0,0,0,0,2831,1567,1264
4,C2308,0,0,0,INDIA,Total,9,20868238,10770638,10097600,...,0,0,0,0,0,0,0,1454,841,613

Selección de columnas del df_Educ

In [9]:
# Para facilitar la lectura de las variables educativas, voy a simplificar sus nombres.
# Printeo los nombres de dichas columnas:
print(df_Educ.columns.tolist())

['Table Name', 'State Code', 'District Code', 'Tehsil Code', 'Area Name', 'Total/ Rural/ Urban', 'Age-group', 'Total - Persons', 'Total - Males', 'Total - Females', 'Illiterate - Persons', 'Illiterate - Males', 'Illiterate - Females', 'Literate - Persons', 'Literate - Males', 'Literate - Females', 'Educational level - Literate without educational level - Persons', 'Educational level - Literate without educational level - Males', 'Educational level - Literate without educational level - Females', 'Educational level - Below primary - Persons', 'Educational level - Below primary - Males', 'Educational level - Below primary - Females', 'Educational level - Primary - Persons', 'Educational level - Primary - Males', 'Educational level - Primary - Females', 'Educational level - Middle - Persons', 'Educational level - Middle - Males', 'Educational level - Middle - Females', 'Educational level - Matric/Secondary - Persons', 'Educational level - Matric/Secondary - Males', 'Educational level - Matric/Secondary - Females', 'Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Persons', 'Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Males', 'Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Females', 'Educational level - Non-technical diploma or certificate not equal to degree - Persons', 'Educational level - Non-technical diploma or certificate not equal to degree - Males', 'Educational level - Non-technical diploma or certificate not equal to degree - Females', 'Educational level - Technical diploma or certificate not equal to degree - Persons', 'Educational level - Technical diploma or certificate not equal to degree - Males', 'Educational level - Technical diploma or certificate not equal to degree - Females', 'Educational level - Graduate & above - Persons', 'Educational level - Graduate & above - Males', 'Educational level - Graduate & above - Females', 'Educational level - Unclassified - Persons', 'Educational level - Unclassified - Males', 'Educational level - Unclassified - Females']

In [10]:
# Renombro las variables:
df_Educ = df_Educ.rename(columns={
"Educational level - Literate without educational level - Persons":"Literate w/o education level - Persons",
"Educational level - Literate without educational level - Males":"Literate w/o education level - Males",
"Educational level - Literate without educational level - Females":"Literate w/o education level - Females",
"Educational level - Below primary - Persons":"Bellow primary - Persons",
"Educational level - Below primary - Males":"Bellow primary - Males",
"Educational level - Below primary - Females":"Bellow primary - Females",
"Educational level - Primary - Persons":"Primary - Persons",
"Educational level - Primary - Males":"Primary - Males",
"Educational level - Primary - Females":"Primary - Females",
"Educational level - Middle - Persons":"Middle - Persons",
"Educational level - Middle - Males":"Middle - Males",
"Educational level - Middle - Females":"Middle - Females",
"Educational level - Matric/Secondary - Persons":"Matric/Secondary - Persons",
"Educational level - Matric/Secondary - Males":"Matric/Secondary - Males",
"Educational level - Matric/Secondary - Females":"Matric/Secondary - Females",
"Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Persons":"Higher second/Interm/Pre-University/Senior second - Persons",
"Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Males":"Higher second/Interm/Pre-University/Senior second - Males",
"Educational level - Higher secondary/Intermediate/Pre-University/Senior secondary - Females":"Higher second/Interm/Pre-University/Senior second - Females",
"Educational level - Non-technical diploma or certificate not equal to degree - Persons":"Non-technical diploma - Persons",
"Educational level - Non-technical diploma or certificate not equal to degree - Males":"Non-technical diploma - Males",
"Educational level - Non-technical diploma or certificate not equal to degree - Females":"Non-technical diploma - Females",
"Educational level - Technical diploma or certificate not equal to degree - Persons":"Technical diploma - Persons",
"Educational level - Technical diploma or certificate not equal to degree - Males":"Technical diploma - Males",
"Educational level - Technical diploma or certificate not equal to degree - Females":"Technical diploma - Females",
"Educational level - Graduate & above - Persons":"Graduate_Persons",
"Educational level - Graduate & above - Males":"Graduate_Males",
"Educational level - Graduate & above - Females":"Graduate_Females",
"Educational level - Unclassified - Persons":"Unclassified_Persons",
"Educational level - Unclassified - Males":"Unclassified_Males",
"Educational level - Unclassified - Females":"Unclassified_Females"
})

Hecho esto, y tal como vimos en el apartado del Análisis preliminar, es necesario hacer otras modificaciones:

Elimino registros que duplican personas:

1. Elimino los registros = 'All ages', 
   los registros con Area Name = 'INDIA' 
   y me quedo con ['Total/ Rural/ Urban'] = Total. No voy a hacer el análisis diferenciando esta variable.
   
A continuación, elimino variables que no aportan valor:

2. Procedo a eliminar las variables que hemos comprobado que no aportaban valor (Table Name, State Code, District Code, Tehsil Code)

In [11]:
# Defino un nuevo df: df_Educ_clean:

df_Educ_clean = df_Educ[
    (df_Educ['Total/ Rural/ Urban'] == 'Total') &
    (df_Educ['Age-group'] != 'All ages') &
    (df_Educ['Area Name'] != 'INDIA') # evita el agregado nacional
].copy()

In [12]:
# Elimino las columnas que no me aportan valor

df_Educ_clean = df_Educ_clean.drop(
    columns=['Table Name', 'State Code', 'District Code', 'Tehsil Code'],
    errors='ignore'
)

In [13]:
print(f"Filas: {df_Educ_clean.shape[0]}")
print(f"Columnas: {df_Educ_clean.shape[1]}")
print(f"Población total: {df_Educ_clean['Total - Persons'].sum():,.0f}")

Filas: 980
Columnas: 42
Población total: 1,028,610,328

Tras esta limpieza, ya obtengo que el total poblacional se aproxima bastante al censo del 2011: 1.200M

JUSTIFICACIÓN:

El dataset contiene tres niveles de agregación que duplican personas:

1. Total/Rural/Urban → nos quedamos solo con 'Total'

2. Age-group 'All ages' → es la suma del resto de grupos de edad

3. Area Name 'INDIA' → es la suma de todos los estados

Tras esta limpieza, cada persona aparece exactamente una vez.

Continuo verificando otro detalle: La variable Literate - Persons no es una variable cualquiera ni aislada. Vamos a comprobarlo:

In [14]:
# selecciono estas variables, exceptuando "Literate - Persons":
education_cols = [
    "Illiterate - Persons",
    "Literate w/o education level - Persons",
    "Bellow primary - Persons",
    "Primary - Persons",
    "Middle - Persons",
    "Matric/Secondary - Persons",
    "Higher second/Interm/Pre-University/Senior second - Persons",
    "Non-technical diploma - Persons",
    "Technical diploma - Persons",
    "Graduate_Persons",
    "Unclassified_Persons",
]

In [15]:
edu_totals = pd.Series(
    {col: df_Educ_clean[col].sum() for col in education_cols}
)

edu_totals.index = [
    "Illiterate",
    "Literate w/o level",
    "Below Primary",
    "Primary",
    "Middle",
    "Matric/Secondary",
    "Higher Secondary",
    "Non-technical diploma",
    "Technical diploma",
    "Graduate & above",
    "Unclassified",
]

In [16]:
df_Educ_clean.columns.tolist()

['Area Name',
 'Total/ Rural/ Urban',
 'Age-group',
 'Total - Persons',
 'Total - Males',
 'Total - Females',
 'Illiterate - Persons',
 'Illiterate - Males',
 'Illiterate - Females',
 'Literate - Persons',
 'Literate - Males',
 'Literate - Females',
 'Literate w/o education level - Persons',
 'Literate w/o education level - Males',
 'Literate w/o education level - Females',
 'Bellow primary - Persons',
 'Bellow primary - Males',
 'Bellow primary - Females',
 'Primary - Persons',
 'Primary - Males',
 'Primary - Females',
 'Middle - Persons',
 'Middle - Males',
 'Middle - Females',
 'Matric/Secondary - Persons',
 'Matric/Secondary - Males',
 'Matric/Secondary - Females',
 'Higher second/Interm/Pre-University/Senior second - Persons',
 'Higher second/Interm/Pre-University/Senior second - Males',
 'Higher second/Interm/Pre-University/Senior second - Females',
 'Non-technical diploma - Persons',
 'Non-technical diploma - Males',
 'Non-technical diploma - Females',
 'Technical diploma - Persons',
 'Technical diploma - Males',
 'Technical diploma - Females',
 'Graduate_Persons',
 'Graduate_Males',
 'Graduate_Females',
 'Unclassified_Persons',
 'Unclassified_Males',
 'Unclassified_Females']

In [17]:
print(edu_totals.to_string())
print(f"\nTotal acumulado: {edu_totals.sum():,.0f}")

Illiterate               467922531
Literate w/o level        20022966
Below Primary            144831273
Primary                  146740047
Middle                    90226846
Matric/Secondary          79229721
Higher Secondary          37816215
Non-technical diploma       386146
Technical diploma          3666680
Graduate & above          37670147
Unclassified                 97756

Total acumulado: 1,028,610,328

In [18]:
# Validación: el total educativo debe coincidir con el total poblacional
assert df_Educ_clean[education_cols].sum().sum() == df_Educ_clean['Total - Persons'].sum()
print(f"Filas tras limpieza: {len(df_Educ_clean)}")
print(f"Población total: {df_Educ_clean['Total - Persons'].sum():,.0f}")

Filas tras limpieza: 980
Población total: 1,028,610,328

In [19]:
# Verificación de coherencia interna del dataset: La variable "Literate - persons" es un agregado (suma de todos los niveles educativos desde
# Literate w/o educational level hasta Unclassified)
print("Literate - Persons (total):", df_Educ_clean["Literate - Persons"].sum())
print("Suma niveles educativos detallados:", df_Educ_clean[[
     "Literate w/o education level - Persons",
     "Bellow primary - Persons",
     "Primary - Persons",
     "Middle - Persons",
     "Matric/Secondary - Persons",
     "Higher second/Interm/Pre-University/Senior second - Persons",
     "Non-technical diploma - Persons",
     "Technical diploma - Persons",
     "Graduate_Persons",
     "Unclassified_Persons",
]].sum().sum())

Literate - Persons (total): 560687797
Suma niveles educativos detallados: 560687797

Se valida así que la variable "Literate - Persons" engloba todos los niveles educativos desde "Literate w/o educational level hasta "Unclassified"

In [20]:
df_Educ_clean.head()

,Area Name,Total/ Rural/ Urban,Age-group,Total - Persons,Total - Males,Total - Females,Illiterate - Persons,Illiterate - Males,Illiterate - Females,Literate - Persons,...,Non-technical diploma - Females,Technical diploma - Persons,Technical diploma - Males,Technical diploma - Females,Graduate_Persons,Graduate_Males,Graduate_Females,Unclassified_Persons,Unclassified_Males,Unclassified_Females
88,State - JAMMU & KASHMIR 01,Total,0-6,1485803,765394,720409,1485803,765394,720409,0,...,0,0,0,0,0,0,0,0,0,0
89,State - JAMMU & KASHMIR 01,Total,7,217317,111487,105830,106713,50665,56048,110604,...,0,0,0,0,0,0,0,13,3,10
90,State - JAMMU & KASHMIR 01,Total,8,321662,165379,156283,129296,58503,70793,192366,...,0,0,0,0,0,0,0,16,8,8
91,State - JAMMU & KASHMIR 01,Total,9,231584,119404,112180,72575,31514,41061,159009,...,0,0,0,0,0,0,0,10,5,5
92,State - JAMMU & KASHMIR 01,Total,10,368272,190872,177400,115170,48744,66426,253102,...,0,0,0,0,0,0,0,17,11,6

Siguiendo con la limpieza de datos, la variable "Age - group" debemos mejorarla. Ya que mezcla edades numéricas, rangos de edad, incluso persenta literales como 'Age not stated'.

También deberemos normalizar de alguna manera la variable "Area Name" para quedarme solo con el nombre del estado.

Empezamos con la variable "Age-group":

In [21]:
print("Valores únicos de Age-group:")
print(df_Educ_clean['Age-group'].unique())

print("\nValores únicos de Area Name:")
print(df_Educ_clean['Area Name'].unique())

Valores únicos de Age-group:
['0-6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19'
 '20-24' '25-29' '30-34' '35-39' '40-44' '45-49' '50-54' '55-59' '60-64'
 '65-69' '70-74' '75-79' '80+' 'Age not stated']

Valores únicos de Area Name:
['State - JAMMU & KASHMIR  01' 'State - HIMACHAL PRADESH  02'
 'State - PUNJAB  03' 'State - CHANDIGARH  04' 'State - UTTARANCHAL  05'
 'State - HARYANA  06' 'State - DELHI  07' 'State - RAJASTHAN  08'
 'State - UTTAR PRADESH  09' 'State - BIHAR  10' 'State - SIKKIM  11'
 'State - ARUNACHAL PRADESH  12' 'State - NAGALAND  13'
 'State - MANIPUR  14' 'State - MIZORAM  15' 'State - TRIPURA  16'
 'State - MEGHALAYA  17' 'State - ASSAM  18' 'State - WEST BENGAL  19'
 'State - JHARKHAND  20' 'State - ORISSA  21' 'State - CHHATTISGARH  22'
 'State - MADHYA PRADESH  23' 'State - GUJARAT  24'
 'State - DAMAN & DIU  25' 'State - DADRA & NAGAR HAVELI  26'
 'State - MAHARASHTRA  27' 'State - ANDHRA PRADESH  28'
 'State - KARNATAKA  29' 'State - GOA  30' 'State - LAKSHADWEEP  31'
 'State - KERALA  32' 'State - TAMIL NADU  33' 'State - PONDICHERRY  34'
 'State - ANDAMAN & NICOBAR ISLANDS  35']

In [22]:
## 1. Normalizamos Area Name:

df_Educ_clean['Area Name'] = (
    df_Educ_clean['Area Name']
    .str.replace('State - ', '', regex=False)  # quita el prefijo
    .str.replace(r'\s+\d+$', '', regex=True)   # quita el número del final
    .str.strip()                               # quita espacios sobrantes
)

print(df_Educ_clean['Area Name'].unique())

['JAMMU & KASHMIR' 'HIMACHAL PRADESH' 'PUNJAB' 'CHANDIGARH' 'UTTARANCHAL'
 'HARYANA' 'DELHI' 'RAJASTHAN' 'UTTAR PRADESH' 'BIHAR' 'SIKKIM'
 'ARUNACHAL PRADESH' 'NAGALAND' 'MANIPUR' 'MIZORAM' 'TRIPURA' 'MEGHALAYA'
 'ASSAM' 'WEST BENGAL' 'JHARKHAND' 'ORISSA' 'CHHATTISGARH'
 'MADHYA PRADESH' 'GUJARAT' 'DAMAN & DIU' 'DADRA & NAGAR HAVELI'
 'MAHARASHTRA' 'ANDHRA PRADESH' 'KARNATAKA' 'GOA' 'LAKSHADWEEP' 'KERALA'
 'TAMIL NADU' 'PONDICHERRY' 'ANDAMAN & NICOBAR ISLANDS']

In [23]:
## 2. Normalizamos Age-group generando rangos de edad:

def clasificar_edad(x):
    if x == 'Age not stated':
        return 'desconocido'
    elif x == '0-6':
        return 'infancia'
    elif x in ['7','8','9','10','11','12','13','14']:
        return 'ninez'
    elif x in ['15','16','17','18','19']:
        return 'adolescencia'
    elif x in ['20-24','25-29']:
        return 'juventud'
    elif x in ['30-34','35-39','40-44','45-49']:
        return 'adulto'
    elif x in ['50-54','55-59','60-64']:
        return 'adulto_mayor'
    else:  # 65-69, 70-74, 75-79, 80+
        return 'tercera_edad'

df_Educ_clean['age_group'] = df_Educ_clean['Age-group'].apply(clasificar_edad)

print(df_Educ_clean['age_group'].value_counts())

age_group
ninez           280
adolescencia    175
tercera_edad    140
adulto          140
adulto_mayor    105
juventud         70
infancia         35
desconocido      35
Name: count, dtype: int64

Hecho esto, de cara a que el cruce con el otro df del Ranking resulte exitoso, tengo que tener en cuenta la variable
por la que voy a hacer ese cruce. La variable común es el Estado. Necesito saber si voy a tener problemas de formato.

In [24]:
# leo el fichero df_Rank_final
df_Rank_final2.tail()

,Institute ID,Institute Name,TLR,RPC,GO,OI,PERCEPTION,City,State,Score,Rank,Año
495,IR-O-U-0217,Christ University,56.19,28.34,65.44,74.23,37.84,Bengaluru,Karnataka,49.65,96,2025
496,IR-O-U-0055,National Institute of Technology Silchar,53.21,45.07,70.76,54.17,4.63,Silchar,Assam,49.51,97,2025
497,IR-O-U-0749,Manipal University Jaipur,63.48,33.80,64.04,66.76,7.11,Jaipur,Rajasthan,49.38,98,2025
498,IR-O-U-0739,Madan Mohan Malaviya University of Technology,67.91,18.82,70.37,71.73,18.48,Gorakhpur,Uttar Pradesh,49.11,99,2025
499,IR-O-U-0688,All India Institute of Medical Sciences Bhuban...,69.14,25.45,58.25,69.89,20.28,Khordha,Odisha,49.04,100,2025

In [25]:
# Veo los valores únicos de la variable State (ya la normalicé en el análisis preliminar):
print(df_Rank_final2['State'].unique())

['Tamil Nadu' 'Karnataka' 'Maharashtra' 'Delhi' 'Uttar Pradesh'
 'West Bengal' 'Uttarakhand' 'Assam' 'Telangana' 'Jharkhand' 'Rajasthan'
 'Madhya Pradesh' 'Punjab' 'Gujarat' 'Odisha' 'Chandigarh' 'Kerala'
 'Andhra Pradesh' 'Bihar' 'Jammu and Kashmir' 'Himachal Pradesh'
 'Pondicherry' 'Meghalaya']

In [26]:
# Tengo que normalizar por tanto la variable 'Area Name' del df_Educ_clean para que ambas variables coincidan

# Paso 1: homogeneizar mayúsculas
df_Educ_clean['Area Name'] = df_Educ_clean['Area Name'].str.title()

# Paso 2: corregir los 3 casos especiales. 
df_Educ_clean['Area Name'] = df_Educ_clean['Area Name'].replace({
    'Jammu & Kashmir'        : 'Jammu and Kashmir', # reemplazo el simbolo '&' por 'and'
    'Uttaranchal'            : 'Uttarakhand',  # ha cambiado el nombre
    'Orissa'                 : 'Odisha',       # ha cambiado el nombre
})

print(df_Educ_clean['Area Name'].unique())

['Jammu and Kashmir' 'Himachal Pradesh' 'Punjab' 'Chandigarh'
 'Uttarakhand' 'Haryana' 'Delhi' 'Rajasthan' 'Uttar Pradesh' 'Bihar'
 'Sikkim' 'Arunachal Pradesh' 'Nagaland' 'Manipur' 'Mizoram' 'Tripura'
 'Meghalaya' 'Assam' 'West Bengal' 'Jharkhand' 'Odisha' 'Chhattisgarh'
 'Madhya Pradesh' 'Gujarat' 'Daman & Diu' 'Dadra & Nagar Haveli'
 'Maharashtra' 'Andhra Pradesh' 'Karnataka' 'Goa' 'Lakshadweep' 'Kerala'
 'Tamil Nadu' 'Pondicherry' 'Andaman & Nicobar Islands']

In [27]:
print(df_Rank_final2['State'].unique())

['Tamil Nadu' 'Karnataka' 'Maharashtra' 'Delhi' 'Uttar Pradesh'
 'West Bengal' 'Uttarakhand' 'Assam' 'Telangana' 'Jharkhand' 'Rajasthan'
 'Madhya Pradesh' 'Punjab' 'Gujarat' 'Odisha' 'Chandigarh' 'Kerala'
 'Andhra Pradesh' 'Bihar' 'Jammu and Kashmir' 'Himachal Pradesh'
 'Pondicherry' 'Meghalaya']

In [28]:
df_Educ_clean.head()

,Area Name,Total/ Rural/ Urban,Age-group,Total - Persons,Total - Males,Total - Females,Illiterate - Persons,Illiterate - Males,Illiterate - Females,Literate - Persons,...,Technical diploma - Persons,Technical diploma - Males,Technical diploma - Females,Graduate_Persons,Graduate_Males,Graduate_Females,Unclassified_Persons,Unclassified_Males,Unclassified_Females,age_group
88,Jammu and Kashmir,Total,0-6,1485803,765394,720409,1485803,765394,720409,0,...,0,0,0,0,0,0,0,0,0,infancia
89,Jammu and Kashmir,Total,7,217317,111487,105830,106713,50665,56048,110604,...,0,0,0,0,0,0,13,3,10,ninez
90,Jammu and Kashmir,Total,8,321662,165379,156283,129296,58503,70793,192366,...,0,0,0,0,0,0,16,8,8,ninez
91,Jammu and Kashmir,Total,9,231584,119404,112180,72575,31514,41061,159009,...,0,0,0,0,0,0,10,5,5,ninez
92,Jammu and Kashmir,Total,10,368272,190872,177400,115170,48744,66426,253102,...,0,0,0,0,0,0,17,11,6,ninez

Otro detalle importante que veo: El df_Rank_final2 tiene 23 estados frente al df_Educ_clean que tiene 35

In [ ]:
print("Estados en df_Educ_clean:", df_Educ_clean['Area Name'].nunique())
print("Estados en df_Rank_final2:", df_Rank_final2['State'].nunique())

Estados en df_Educ_clean: 35
Estados en df_Rank_final: 23

Entonces, decido que en lugar de eliminar los Estados no coincidentes, los voy a incluir indicando que 
"no tienen universidades en el ranking" y quedarán sin cruzar.

In [30]:
# Al cruzarlo con df_Educ_clean, voy a verificar que no hay nada más raro en la variable común. sé que hay 12 estados que no coinciden
# en los dos df pero tambien me puedo encontrar con estados no comunes:

# Ver qué estados del ranking NO encuentran match en Educ
estados_rank = set(df_Rank_final2['State'].unique())
estados_educ = set(df_Educ_clean['Area Name'].unique())

print("Está en Rank pero NO en Educ:")
print(estados_rank - estados_educ)

print("\nEstá en Educ pero NO en Rank:")
print(estados_educ - estados_rank)

Está en Rank pero NO en Educ:
{'Telangana'}

Está en Educ pero NO en Rank:
{'Haryana', 'Mizoram', 'Dadra & Nagar Haveli', 'Andaman & Nicobar Islands', 'Nagaland', 'Sikkim', 'Arunachal Pradesh', 'Chhattisgarh', 'Lakshadweep', 'Goa', 'Tripura', 'Daman & Diu', 'Manipur'}

El estado de Telangana está en el df_Rank_final pero no en df_Educ_clean — probablemente porque en el censo del 2011 el estado de Telangana 
aún estaba unido a Andhra Pradesh (se separó en 2014).

Decido que como el df_Educ_clean es el df principal, voy a excluir el estado de Telanga del análisis.

Ahora sí puedo hacer la fusión de ambos dataframes.

In [31]:
# Voy a eliminar las columnas "Total/Rural/Urban" y "age-group", ya que son redundantes y no me aportan nada tras la limpieza 
# que hemos hecho de ambas:
df_Educ_clean = df_Educ_clean.drop(columns=["Age-group"])

In [32]:
df_Educ_clean = df_Educ_clean.drop(columns=["Total/ Rural/ Urban"])

In [33]:
df_Educ_clean.duplicated().sum()

np.int64(0)

In [34]:
# Guardo el datset df_Educ_clean:
df_Educ_clean.to_csv('../data/output/df_Educ_clean.csv',index=False)

In [35]:
# Guardo el dataset df_Rank_final2:
df_Rank_final2.to_csv('../data/output/df_Rank_final2.csv',index=False)

# Fusión de los dos df: df_Educ_clean y df_Rank_final2

Tal como dijimos anteriormente, para obtener una métrica representativa del ranking de cada estado para cruzarla con el dataframe de educación (df_Educ_clean), voy a calcular el promedio de los 5 años. 

Para ello, creo un nuevo dataframe "df_Rank_state" a partir de df_Rank_final2

In [36]:
# Agrupar ranking por estado (promedio de los 5 años)
df_Rank_state = df_Rank_final2.groupby('State').agg(
    Score_mean=('Score', 'mean'),
    Score_std=('Score', 'std'),
    Rank_mean=('Rank', 'mean'),
    TLR_mean=('TLR', 'mean'),
    RPC_mean=('RPC', 'mean'),
    GO_mean=('GO', 'mean'),
    OI_mean=('OI', 'mean'),
    PERCEPTION_mean=('PERCEPTION', 'mean'),
    n_institutos=('Institute ID', 'count')  # me devuelve el total de univ. por Estado
).reset_index()

print(df_Rank_state.shape)  # Esto me devolverá 23 estados
df_Rank_state.head()

(23, 10)

,State,Score_mean,Score_std,Rank_mean,TLR_mean,RPC_mean,GO_mean,OI_mean,PERCEPTION_mean,n_institutos
0,Andhra Pradesh,50.502500,4.467945,60.416667,62.400833,30.123333,78.025833,60.386667,11.012500,12
1,Assam,54.645625,10.366683,55.562500,62.683125,42.369375,76.821250,57.801875,19.825625,16
2,Bihar,50.558333,3.732037,64.000000,62.388333,38.158333,65.508333,57.880000,15.056667,6
3,Chandigarh,53.606667,3.124162,45.500000,55.536667,44.821667,72.016667,61.863333,29.160000,6
4,Delhi,62.854444,11.335680,28.777778,66.755278,51.135833,80.800000,68.135556,45.155833,36

Ultimo paso: Como dijimos también anteriormente, necesito tener el df_Educ_clean a nivel estado, es decir, un estado por fila, con el fin de fusionarlo con el df_Rank_state.

Agregar df_Educ_clean a nivel estado (es eliminar Age_group implícitamente) para obtener así una fila por estado
y poderlo fusionar con df_Rank_state.

In [37]:
df_Educ_state = (
    df_Educ_clean
    .groupby("Area Name")
    .sum(numeric_only=True)
    .reset_index()
)

In [38]:
df_Educ_clean.head()

,Area Name,Total - Persons,Total - Males,Total - Females,Illiterate - Persons,Illiterate - Males,Illiterate - Females,Literate - Persons,Literate - Males,Literate - Females,...,Technical diploma - Persons,Technical diploma - Males,Technical diploma - Females,Graduate_Persons,Graduate_Males,Graduate_Females,Unclassified_Persons,Unclassified_Males,Unclassified_Females,age_group
88,Jammu and Kashmir,1485803,765394,720409,1485803,765394,720409,0,0,0,...,0,0,0,0,0,0,0,0,0,infancia
89,Jammu and Kashmir,217317,111487,105830,106713,50665,56048,110604,60822,49782,...,0,0,0,0,0,0,13,3,10,ninez
90,Jammu and Kashmir,321662,165379,156283,129296,58503,70793,192366,106876,85490,...,0,0,0,0,0,0,16,8,8,ninez
91,Jammu and Kashmir,231584,119404,112180,72575,31514,41061,159009,87890,71119,...,0,0,0,0,0,0,10,5,5,ninez
92,Jammu and Kashmir,368272,190872,177400,115170,48744,66426,253102,142128,110974,...,0,0,0,0,0,0,17,11,6,ninez

In [39]:
df_Educ_state.head()

,Area Name,Total - Persons,Total - Males,Total - Females,Illiterate - Persons,Illiterate - Males,Illiterate - Females,Literate - Persons,Literate - Males,Literate - Females,...,Non-technical diploma - Females,Technical diploma - Persons,Technical diploma - Males,Technical diploma - Females,Graduate_Persons,Graduate_Males,Graduate_Females,Unclassified_Persons,Unclassified_Males,Unclassified_Females
0,Andaman & Nicobar Islands,356152,192972,163180,103017,46141,56876,253135,146831,106304,...,21,2647,1857,790,14903,8905,5998,17,13,4
1,Andhra Pradesh,76210007,38527413,37682594,36275684,15082625,21193059,39934323,23444788,16489535,...,10121,389404,346447,42957,2826363,2032949,793414,3692,2492,1200
2,Arunachal Pradesh,1097968,579941,518027,613183,276660,336523,484785,303281,181504,...,16,2573,2342,231,26047,19533,6514,34,28,6
3,Assam,26655528,13777037,12878491,12640174,5588340,7051834,14015354,8188697,5826657,...,225,21732,19493,2239,678887,473802,205085,2635,1902,733
4,Bihar,82998509,43243795,39754714,51888932,22599419,29289513,31109577,20644376,10465201,...,4901,48532,40458,8074,2109415,1737651,371764,18675,14043,4632

In [40]:
# Creo columnas adicionales con la tasa educativa. Para ello, convierto a porcentajes las variables numéricas,

# Lista de columnas de educación
columns = [
"Illiterate - Persons",
"Illiterate - Males",
"Illiterate - Females",
"Literate - Persons",
"Literate - Males",
"Literate - Females",
"Literate w/o education level - Persons",
"Literate w/o education level - Males",
"Literate w/o education level - Females",
"Bellow primary - Persons",
"Bellow primary - Males",
"Bellow primary - Females",
"Primary - Persons",
"Primary - Males",
"Primary - Females",
"Middle - Persons",
"Middle - Males",
"Middle - Females",
"Matric/Secondary - Persons",
"Matric/Secondary - Males",
"Matric/Secondary - Females",
"Higher second/Interm/Pre-University/Senior second - Persons",
"Higher second/Interm/Pre-University/Senior second - Males",
"Higher second/Interm/Pre-University/Senior second - Females",
"Non-technical diploma - Persons",
"Non-technical diploma - Males",
"Non-technical diploma - Females",
"Technical diploma - Persons",
"Technical diploma - Males",
"Technical diploma - Females",
"Graduate_Persons",
"Graduate_Males",
"Graduate_Females",
"Unclassified_Persons",
"Unclassified_Males",
"Unclassified_Females"
]

# Mapeamos cada sufijo con su denominador correspondiente
denominator_map = {
    "Persons": "Total - Persons",
    "Males":   "Total - Males",
    "Females": "Total - Females"
}

# Creamos columnas de tasa con el denominador correcto según el género
for col in columns:
    # Detectamos el separador (" - " o "_") para extraer el sufijo de género
    if " - " in col:
        base, gender = col.rsplit(" - ", 1)
    else:
        base, gender = col.rsplit("_", 1)

    denominator = denominator_map[gender]
    new_col = base.lower().replace(" ", "_").replace("/", "_") + f"_{gender.lower()}_rate"
    df_Educ_state[new_col] = df_Educ_state[col] / df_Educ_state[denominator]

# Resultado final
df_Educ_state.head()

,Area Name,Total - Persons,Total - Males,Total - Females,Illiterate - Persons,Illiterate - Males,Illiterate - Females,Literate - Persons,Literate - Males,Literate - Females,...,non-technical_diploma_females_rate,technical_diploma_persons_rate,technical_diploma_males_rate,technical_diploma_females_rate,graduate_persons_rate,graduate_males_rate,graduate_females_rate,unclassified_persons_rate,unclassified_males_rate,unclassified_females_rate
0,Andaman & Nicobar Islands,356152,192972,163180,103017,46141,56876,253135,146831,106304,...,0.000129,0.007432,0.009623,0.004841,0.041844,0.046147,0.036757,0.000048,0.000067,0.000025
1,Andhra Pradesh,76210007,38527413,37682594,36275684,15082625,21193059,39934323,23444788,16489535,...,0.000269,0.005110,0.008992,0.001140,0.037087,0.052766,0.021055,0.000048,0.000065,0.000032
2,Arunachal Pradesh,1097968,579941,518027,613183,276660,336523,484785,303281,181504,...,0.000031,0.002343,0.004038,0.000446,0.023723,0.033681,0.012575,0.000031,0.000048,0.000012
3,Assam,26655528,13777037,12878491,12640174,5588340,7051834,14015354,8188697,5826657,...,0.000017,0.000815,0.001415,0.000174,0.025469,0.034391,0.015925,0.000099,0.000138,0.000057
4,Bihar,82998509,43243795,39754714,51888932,22599419,29289513,31109577,20644376,10465201,...,0.000123,0.000585,0.000936,0.000203,0.025415,0.040183,0.009351,0.000225,0.000325,0.000117

Merge definitivo: df_Educ_state con df_Rank_state

In [41]:
# Merge definitivo: contiene df_Educ_state y df_Rank_state
df_merged = df_Educ_state.merge(
    df_Rank_state,
    left_on='Area Name',
    right_on='State',
    how='left'
)

df_merged['tiene_ranking'] = df_merged['Score_mean'].notna()

print(f"Estados únicos: {df_merged['Area Name'].nunique()}")  # 35
print(f"Estados con ranking: {df_merged[df_merged['tiene_ranking']]['Area Name'].nunique()}")  # 22 (Telangana queda fuera del analisis)

Estados únicos: 35
Estados con ranking: 22

Con esto obtengo un dataframe basado en estadísticas de los diferentes niveles educativos diferenciados por estados y los promedios de los principales indicadores educativos del NIRF de los estados de la India.

Con este df haré parte del EDA requerido.

In [42]:
## guardo el df tras el analisis preliminar y limpieza:
df_merged.to_csv('../data/output/df_merged.csv',index=False)

In [43]:
## guardo el df tras el analisis preliminar y limpieza:
df_Rank_state.to_csv('../data/output/df_Rank_state.csv',index=False)

In [44]:
## guardo el df tras el analisis preliminar y limpieza:
df_Educ_state.to_csv('../data/output/df_Educ_state.csv',index=False)

In [ ]:
################### FIN DE LA LIMPIEZA ###############